--------------------------------------------------------
--  File created - 星期四-十一月-01-2018   
--------------------------------------------------------
  DROP TABLE "ERPUSER"."DEP" cascade constraints;
  DROP TABLE "ERPUSER"."EMP" cascade constraints;
  DROP TABLE "ERPUSER"."EMP_ROLE" cascade constraints;
  DROP TABLE "ERPUSER"."GOODS" cascade constraints;
  DROP TABLE "ERPUSER"."GOODSTYPE" cascade constraints;
  DROP TABLE "ERPUSER"."INVENTORY" cascade constraints;
  DROP TABLE "ERPUSER"."MENU" cascade constraints;
  DROP TABLE "ERPUSER"."ORDERDETAIL" cascade constraints;
  DROP TABLE "ERPUSER"."ORDERS" cascade constraints;
  DROP TABLE "ERPUSER"."RETURNORDERDETAIL" cascade constraints;
  DROP TABLE "ERPUSER"."RETURNORDERS" cascade constraints;
  DROP TABLE "ERPUSER"."ROLE" cascade constraints;
  DROP TABLE "ERPUSER"."ROLE_MENU" cascade constraints;
  DROP TABLE "ERPUSER"."STORE" cascade constraints;
  DROP TABLE "ERPUSER"."STOREDETAIL" cascade constraints;
  DROP TABLE "ERPUSER"."STOREOPER" cascade constraints;
  DROP TABLE "ERPUSER"."SUPPLIER" cascade constraints;
  DROP SEQUENCE "ERPUSER"."DEP_SEQ";
  DROP SEQUENCE "ERPUSER"."EMP_ROLE_SEQ";
  DROP SEQUENCE "ERPUSER"."EMP_SEQ";
  DROP SEQUENCE "ERPUSER"."GOODSTYPE_SEQ";
  DROP SEQUENCE "ERPUSER"."GOODS_SEQ";
  DROP SEQUENCE "ERPUSER"."INVENTORY_SEQ";
  DROP SEQUENCE "ERPUSER"."MENU_SEQ";
  DROP SEQUENCE "ERPUSER"."ORDERDETAIL_SEQ";
  DROP SEQUENCE "ERPUSER"."ORDERS_SEQ";
  DROP SEQUENCE "ERPUSER"."RETURNORDERDETAIL_SEQ";
  DROP SEQUENCE "ERPUSER"."RETURNORDERS_SEQ";
  DROP SEQUENCE "ERPUSER"."ROLE_MENU_SEQ";
  DROP SEQUENCE "ERPUSER"."ROLE_SEQ";
  DROP SEQUENCE "ERPUSER"."STOREDETAIL_SEQ";
  DROP SEQUENCE "ERPUSER"."STOREOPER_SEQ";
  DROP SEQUENCE "ERPUSER"."STORE_SEQ";
  DROP SEQUENCE "ERPUSER"."SUPPLIER_SEQ";
  DROP VIEW "ERPUSER"."VIEW_STOREALERT";
--------------------------------------------------------
--  DDL for Sequence DEP_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "ERPUSER"."DEP_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 21 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence EMP_ROLE_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "ERPUSER"."EMP_ROLE_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 NOCACHE  NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence EMP_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "ERPUSER"."EMP_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 21 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence GOODSTYPE_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "ERPUSER"."GOODSTYPE_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 21 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence GOODS_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "ERPUSER"."GOODS_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 61 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence INVENTORY_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "ERPUSER"."INVENTORY_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 21 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence MENU_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "ERPUSER"."MENU_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence ORDERDETAIL_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "ERPUSER"."ORDERDETAIL_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 81 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence ORDERS_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "ERPUSER"."ORDERS_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 81 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence RETURNORDERDETAIL_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "ERPUSER"."RETURNORDERDETAIL_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 41 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence RETURNORDERS_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "ERPUSER"."RETURNORDERS_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 41 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence ROLE_MENU_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "ERPUSER"."ROLE_MENU_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 4 NOCACHE  NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence ROLE_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "ERPUSER"."ROLE_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 41 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence STOREDETAIL_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "ERPUSER"."STOREDETAIL_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 61 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence STOREOPER_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "ERPUSER"."STOREOPER_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 61 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence STORE_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "ERPUSER"."STORE_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence SUPPLIER_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "ERPUSER"."SUPPLIER_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 21 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Table DEP
--------------------------------------------------------

  CREATE TABLE "ERPUSER"."DEP" 
   (  "UUID" NUMBER(19,0), 
  "NAME" VARCHAR2(255 CHAR), 
  "TELE" VARCHAR2(255 CHAR)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "ERP_TS" ;
--------------------------------------------------------
--  DDL for Table EMP
--------------------------------------------------------

  CREATE TABLE "ERPUSER"."EMP" 
   (  "UUID" NUMBER(19,0), 
  "USERNAME" VARCHAR2(255 CHAR), 
  "PWD" VARCHAR2(255 CHAR), 
  "NAME" VARCHAR2(255 CHAR), 
  "GENDER" NUMBER(19,0), 
  "EMAIL" VARCHAR2(255 CHAR), 
  "TELE" VARCHAR2(255 CHAR), 
  "ADDRESS" VARCHAR2(255 CHAR), 
  "BIRTHDAY" TIMESTAMP (6), 
  "DEPUUID" NUMBER(19,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "ERP_TS" ;
--------------------------------------------------------
--  DDL for Table EMP_ROLE
--------------------------------------------------------

  CREATE TABLE "ERPUSER"."EMP_ROLE" 
   (  "UUID" NUMBER, 
  "EMPUUID" NUMBER, 
  "ROLEUUID" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "ERP_TS" ;
--------------------------------------------------------
--  DDL for Table GOODSTYPE
--------------------------------------------------------

  CREATE TABLE "ERPUSER"."GOODSTYPE" 
   (  "UUID" NUMBER(19,0), 
  "NAME" VARCHAR2(255 CHAR)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "ERP_TS" ;
--------------------------------------------------------
--  DDL for Table GOODS
--------------------------------------------------------

  CREATE TABLE "ERPUSER"."GOODS" 
   (  "UUID" NUMBER(19,0), 
  "NAME" VARCHAR2(255 CHAR), 
  "ORIGIN" VARCHAR2(255 CHAR), 
  "PRODUCER" VARCHAR2(255 CHAR), 
  "UNIT" VARCHAR2(255 CHAR), 
  "INPRICE" FLOAT(126), 
  "OUTPRICE" FLOAT(126), 
  "GOODSTYPEUUID" NUMBER(19,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "ERP_TS" ;
--------------------------------------------------------
--  DDL for Table INVENTORY
--------------------------------------------------------

  CREATE TABLE "ERPUSER"."INVENTORY" 
   (  "UUID" NUMBER(19,0), 
  "GOODSUUID" NUMBER(19,0), 
  "STOREUUID" NUMBER(19,0), 
  "NUM" NUMBER(19,0), 
  "TYPE" VARCHAR2(255 CHAR), 
  "CREATETIME" TIMESTAMP (6), 
  "CHECKTIME" TIMESTAMP (6), 
  "CREATER" NUMBER(19,0), 
  "CHECKER" NUMBER(19,0), 
  "STATE" VARCHAR2(255 CHAR), 
  "REMARK" VARCHAR2(255 CHAR)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "ERP_TS" ;
--------------------------------------------------------
--  DDL for Table MENU
--------------------------------------------------------

  CREATE TABLE "ERPUSER"."MENU" 
   (  "MENUID" VARCHAR2(255 CHAR), 
  "MENUNAME" VARCHAR2(255 CHAR), 
  "ICON" VARCHAR2(255 CHAR), 
  "URL" VARCHAR2(255 CHAR), 
  "PID" VARCHAR2(255 CHAR)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "ERP_TS" ;
--------------------------------------------------------
--  DDL for Table ORDERDETAIL
--------------------------------------------------------

  CREATE TABLE "ERPUSER"."ORDERDETAIL" 
   (  "UUID" NUMBER(19,0), 
  "GOODSUUID" NUMBER(19,0), 
  "GOODSNAME" VARCHAR2(255 CHAR), 
  "PRICE" FLOAT(126), 
  "NUM" NUMBER(19,0), 
  "MONEY" FLOAT(126), 
  "ENDTIME" TIMESTAMP (6), 
  "ENDER" NUMBER(19,0), 
  "STOREUUID" NUMBER(19,0), 
  "STATE" VARCHAR2(255 CHAR), 
  "ORDERSUUID" NUMBER(19,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "ERP_TS" ;
--------------------------------------------------------
--  DDL for Table ORDERS
--------------------------------------------------------

  CREATE TABLE "ERPUSER"."ORDERS" 
   (  "UUID" NUMBER(19,0), 
  "CREATETIME" TIMESTAMP (6), 
  "CHECKTIME" TIMESTAMP (6), 
  "STARTTIME" TIMESTAMP (6), 
  "ENDTIME" TIMESTAMP (6), 
  "TYPE" VARCHAR2(255 CHAR), 
  "CREATER" NUMBER(19,0), 
  "CHECKER" NUMBER(19,0), 
  "STARTER" NUMBER(19,0), 
  "ENDER" NUMBER(19,0), 
  "SUPPLIERUUID" NUMBER(19,0), 
  "TOTALMONEY" FLOAT(126), 
  "STATE" VARCHAR2(255 CHAR), 
  "WAYBILLSN" NUMBER(19,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "ERP_TS" ;
--------------------------------------------------------
--  DDL for Table RETURNORDERDETAIL
--------------------------------------------------------

  CREATE TABLE "ERPUSER"."RETURNORDERDETAIL" 
   (  "UUID" NUMBER(19,0), 
  "GOODSUUID" NUMBER(19,0), 
  "GOODSNAME" VARCHAR2(255 CHAR), 
  "PRICE" FLOAT(126), 
  "NUM" NUMBER(19,0), 
  "MONEY" FLOAT(126), 
  "ENDTIME" TIMESTAMP (6), 
  "ENDER" NUMBER(19,0), 
  "STOREUUID" NUMBER(19,0), 
  "STATE" VARCHAR2(255 CHAR), 
  "ORDERSUUID" NUMBER(19,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "ERP_TS" ;
--------------------------------------------------------
--  DDL for Table RETURNORDERS
--------------------------------------------------------

  CREATE TABLE "ERPUSER"."RETURNORDERS" 
   (  "UUID" NUMBER(19,0), 
  "CREATETIME" TIMESTAMP (6), 
  "CHECKTIME" TIMESTAMP (6), 
  "ENDTIME" TIMESTAMP (6), 
  "TYPE" VARCHAR2(255 CHAR), 
  "CREATER" NUMBER(19,0), 
  "CHECKER" NUMBER(19,0), 
  "ENDER" NUMBER(19,0), 
  "SUPPLIERUUID" NUMBER(19,0), 
  "TOTALMONEY" FLOAT(126), 
  "STATE" VARCHAR2(255 CHAR), 
  "WAYBILLSN" NUMBER(19,0), 
  "ORDERSUUID" NUMBER(19,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "ERP_TS" ;
--------------------------------------------------------
--  DDL for Table ROLE
--------------------------------------------------------

  CREATE TABLE "ERPUSER"."ROLE" 
   (  "UUID" NUMBER(19,0), 
  "NAME" VARCHAR2(255 CHAR)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "ERP_TS" ;
--------------------------------------------------------
--  DDL for Table ROLE_MENU
--------------------------------------------------------

  CREATE TABLE "ERPUSER"."ROLE_MENU" 
   (  "UUID" NUMBER, 
  "ROLEUUID" NUMBER, 
  "MENUUUID" VARCHAR2(10 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "ERP_TS" ;
--------------------------------------------------------
--  DDL for Table STORE
--------------------------------------------------------

  CREATE TABLE "ERPUSER"."STORE" 
   (  "UUID" NUMBER(19,0), 
  "NAME" VARCHAR2(255 CHAR), 
  "EMPUUID" NUMBER(19,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "ERP_TS" ;
--------------------------------------------------------
--  DDL for Table STOREDETAIL
--------------------------------------------------------

  CREATE TABLE "ERPUSER"."STOREDETAIL" 
   (  "UUID" NUMBER(19,0), 
  "STOREUUID" NUMBER(19,0), 
  "GOODSUUID" NUMBER(19,0), 
  "NUM" NUMBER(19,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "ERP_TS" ;
--------------------------------------------------------
--  DDL for Table STOREOPER
--------------------------------------------------------

  CREATE TABLE "ERPUSER"."STOREOPER" 
   (  "UUID" NUMBER(19,0), 
  "EMPUUID" NUMBER(19,0), 
  "OPERTIME" TIMESTAMP (6), 
  "STOREUUID" NUMBER(19,0), 
  "GOODSUUID" NUMBER(19,0), 
  "NUM" NUMBER(19,0), 
  "TYPE" VARCHAR2(255 CHAR)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "ERP_TS" ;
--------------------------------------------------------
--  DDL for Table SUPPLIER
--------------------------------------------------------

  CREATE TABLE "ERPUSER"."SUPPLIER" 
   (  "UUID" NUMBER(19,0), 
  "NAME" VARCHAR2(255 CHAR), 
  "ADDRESS" VARCHAR2(255 CHAR), 
  "CONTACT" VARCHAR2(255 CHAR), 
  "TELE" VARCHAR2(255 CHAR), 
  "EMAIL" VARCHAR2(255 CHAR), 
  "TYPE" VARCHAR2(255 CHAR)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "ERP_TS" ;

---------------------------------------------------
--   DATA FOR TABLE EMP_ROLE
--   FILTER = none used
---------------------------------------------------
REM INSERTING into ERPUSER.EMP_ROLE
Insert into ERPUSER.EMP_ROLE (UUID,EMPUUID,ROLEUUID) values (null,8,2);
Insert into ERPUSER.EMP_ROLE (UUID,EMPUUID,ROLEUUID) values (null,8,23);
Insert into ERPUSER.EMP_ROLE (UUID,EMPUUID,ROLEUUID) values (null,8,24);
Insert into ERPUSER.EMP_ROLE (UUID,EMPUUID,ROLEUUID) values (null,8,25);
Insert into ERPUSER.EMP_ROLE (UUID,EMPUUID,ROLEUUID) values (null,8,27);
Insert into ERPUSER.EMP_ROLE (UUID,EMPUUID,ROLEUUID) values (null,8,21);
Insert into ERPUSER.EMP_ROLE (UUID,EMPUUID,ROLEUUID) values (null,8,22);
Insert into ERPUSER.EMP_ROLE (UUID,EMPUUID,ROLEUUID) values (null,8,26);
Insert into ERPUSER.EMP_ROLE (UUID,EMPUUID,ROLEUUID) values (null,7,24);
Insert into ERPUSER.EMP_ROLE (UUID,EMPUUID,ROLEUUID) values (null,7,26);
Insert into ERPUSER.EMP_ROLE (UUID,EMPUUID,ROLEUUID) values (null,5,21);
Insert into ERPUSER.EMP_ROLE (UUID,EMPUUID,ROLEUUID) values (null,5,22);
Insert into ERPUSER.EMP_ROLE (UUID,EMPUUID,ROLEUUID) values (null,4,27);
Insert into ERPUSER.EMP_ROLE (UUID,EMPUUID,ROLEUUID) values (null,3,25);
Insert into ERPUSER.EMP_ROLE (UUID,EMPUUID,ROLEUUID) values (null,6,23);

---------------------------------------------------
--   END DATA FOR TABLE EMP_ROLE
---------------------------------------------------

---------------------------------------------------
--   DATA FOR TABLE ROLE
--   FILTER = none used
---------------------------------------------------
REM INSERTING into ERPUSER.ROLE
Insert into ERPUSER.ROLE (UUID,NAME) values (2,'超级管理员');
Insert into ERPUSER.ROLE (UUID,NAME) values (23,'库管员');
Insert into ERPUSER.ROLE (UUID,NAME) values (24,'采购主管');
Insert into ERPUSER.ROLE (UUID,NAME) values (25,'仓库主管');
Insert into ERPUSER.ROLE (UUID,NAME) values (27,'总经理');
Insert into ERPUSER.ROLE (UUID,NAME) values (21,'采购员');
Insert into ERPUSER.ROLE (UUID,NAME) values (22,'销售员');
Insert into ERPUSER.ROLE (UUID,NAME) values (26,'销售主管');

---------------------------------------------------
--   END DATA FOR TABLE ROLE
---------------------------------------------------

---------------------------------------------------
--   DATA FOR TABLE DEP
--   FILTER = none used
---------------------------------------------------
REM INSERTING into ERPUSER.DEP
Insert into ERPUSER.DEP (UUID,NAME,TELE) values (2,'管理员组','000000');
Insert into ERPUSER.DEP (UUID,NAME,TELE) values (3,'总裁办','111111');
Insert into ERPUSER.DEP (UUID,NAME,TELE) values (4,'采购部','222222');
Insert into ERPUSER.DEP (UUID,NAME,TELE) values (5,'销售部','333333');
Insert into ERPUSER.DEP (UUID,NAME,TELE) values (6,'公关部','444444');
Insert into ERPUSER.DEP (UUID,NAME,TELE) values (7,'行政部','555555');
Insert into ERPUSER.DEP (UUID,NAME,TELE) values (8,'人事部','555555');
Insert into ERPUSER.DEP (UUID,NAME,TELE) values (9,'运输部','444444');
Insert into ERPUSER.DEP (UUID,NAME,TELE) values (10,'党办','555555');
Insert into ERPUSER.DEP (UUID,NAME,TELE) values (11,'工会','555555');
Insert into ERPUSER.DEP (UUID,NAME,TELE) values (12,'仓储部','555555');
Insert into ERPUSER.DEP (UUID,NAME,TELE) values (13,'客服部','555555');
Insert into ERPUSER.DEP (UUID,NAME,TELE) values (14,'财务部','555555');
Insert into ERPUSER.DEP (UUID,NAME,TELE) values (15,'运营部','555555');
Insert into ERPUSER.DEP (UUID,NAME,TELE) values (16,'神奇四侠','123');

---------------------------------------------------
--   END DATA FOR TABLE DEP
---------------------------------------------------

---------------------------------------------------
--   DATA FOR TABLE ROLE_MENU
--   FILTER = none used
---------------------------------------------------
REM INSERTING into ERPUSER.ROLE_MENU
Insert into ERPUSER.ROLE_MENU (UUID,ROLEUUID,MENUUUID) values (null,21,'101');
Insert into ERPUSER.ROLE_MENU (UUID,ROLEUUID,MENUUUID) values (null,21,'102');
Insert into ERPUSER.ROLE_MENU (UUID,ROLEUUID,MENUUUID) values (null,21,'104');
Insert into ERPUSER.ROLE_MENU (UUID,ROLEUUID,MENUUUID) values (null,21,'301');
Insert into ERPUSER.ROLE_MENU (UUID,ROLEUUID,MENUUUID) values (null,21,'302');
Insert into ERPUSER.ROLE_MENU (UUID,ROLEUUID,MENUUUID) values (null,21,'306');
Insert into ERPUSER.ROLE_MENU (UUID,ROLEUUID,MENUUUID) values (null,21,'307');
Insert into ERPUSER.ROLE_MENU (UUID,ROLEUUID,MENUUUID) values (null,2,'704');
Insert into ERPUSER.ROLE_MENU (UUID,ROLEUUID,MENUUUID) values (null,22,'101');
Insert into ERPUSER.ROLE_MENU (UUID,ROLEUUID,MENUUUID) values (null,22,'102');
Insert into ERPUSER.ROLE_MENU (UUID,ROLEUUID,MENUUUID) values (null,22,'105');
Insert into ERPUSER.ROLE_MENU (UUID,ROLEUUID,MENUUUID) values (null,22,'401');
Insert into ERPUSER.ROLE_MENU (UUID,ROLEUUID,MENUUUID) values (null,22,'402');
Insert into ERPUSER.ROLE_MENU (UUID,ROLEUUID,MENUUUID) values (null,22,'404');
Insert into ERPUSER.ROLE_MENU (UUID,ROLEUUID,MENUUUID) values (null,22,'405');
Insert into ERPUSER.ROLE_MENU (UUID,ROLEUUID,MENUUUID) values (null,22,'501');
Insert into ERPUSER.ROLE_MENU (UUID,ROLEUUID,MENUUUID) values (null,27,'100');
Insert into ERPUSER.ROLE_MENU (UUID,ROLEUUID,MENUUUID) values (null,27,'101');
Insert into ERPUSER.ROLE_MENU (UUID,ROLEUUID,MENUUUID) values (null,27,'102');
Insert into ERPUSER.ROLE_MENU (UUID,ROLEUUID,MENUUUID) values (null,27,'103');
Insert into ERPUSER.ROLE_MENU (UUID,ROLEUUID,MENUUUID) values (null,27,'104');
Insert into ERPUSER.ROLE_MENU (UUID,ROLEUUID,MENUUUID) values (null,27,'105');
Insert into ERPUSER.ROLE_MENU (UUID,ROLEUUID,MENUUUID) values (null,27,'200');
Insert into ERPUSER.ROLE_MENU (UUID,ROLEUUID,MENUUUID) values (null,27,'201');
Insert into ERPUSER.ROLE_MENU (UUID,ROLEUUID,MENUUUID) values (null,27,'202');
Insert into ERPUSER.ROLE_MENU (UUID,ROLEUUID,MENUUUID) values (null,27,'300');
Insert into ERPUSER.ROLE_MENU (UUID,ROLEUUID,MENUUUID) values (null,27,'301');
Insert into ERPUSER.ROLE_MENU (UUID,ROLEUUID,MENUUUID) values (null,27,'302');
Insert into ERPUSER.ROLE_MENU (UUID,ROLEUUID,MENUUUID) values (null,27,'303');
Insert into ERPUSER.ROLE_MENU (UUID,ROLEUUID,MENUUUID) values (null,27,'304');
Insert into ERPUSER.ROLE_MENU (UUID,ROLEUUID,MENUUUID) values (null,27,'305');
Insert into ERPUSER.ROLE_MENU (UUID,ROLEUUID,MENUUUID) values (null,27,'306');
Insert into ERPUSER.ROLE_MENU (UUID,ROLEUUID,MENUUUID) values (null,27,'307');
Insert into ERPUSER.ROLE_MENU (UUID,ROLEUUID,MENUUUID) values (null,27,'308');
Insert into ERPUSER.ROLE_MENU (UUID,ROLEUUID,MENUUUID) values (null,27,'309');
Insert into ERPUSER.ROLE_MENU (UUID,ROLEUUID,MENUUUID) values (null,27,'400');
Insert into ERPUSER.ROLE_MENU (UUID,ROLEUUID,MENUUUID) values (null,27,'401');
Insert into ERPUSER.ROLE_MENU (UUID,ROLEUUID,MENUUUID) values (null,27,'402');
Insert into ERPUSER.ROLE_MENU (UUID,ROLEUUID,MENUUUID) values (null,27,'403');
Insert into ERPUSER.ROLE_MENU (UUID,ROLEUUID,MENUUUID) values (null,27,'404');
Insert into ERPUSER.ROLE_MENU (UUID,ROLEUUID,MENUUUID) values (null,27,'405');
Insert into ERPUSER.ROLE_MENU (UUID,ROLEUUID,MENUUUID) values (null,27,'406');
Insert into ERPUSER.ROLE_MENU (UUID,ROLEUUID,MENUUUID) values (null,27,'407');
Insert into ERPUSER.ROLE_MENU (UUID,ROLEUUID,MENUUUID) values (null,27,'500');
Insert into ERPUSER.ROLE_MENU (UUID,ROLEUUID,MENUUUID) values (null,27,'501');
Insert into ERPUSER.ROLE_MENU (UUID,ROLEUUID,MENUUUID) values (null,27,'502');
Insert into ERPUSER.ROLE_MENU (UUID,ROLEUUID,MENUUUID) values (null,27,'503');
Insert into ERPUSER.ROLE_MENU (UUID,ROLEUUID,MENUUUID) values (null,2,'100');
Insert into ERPUSER.ROLE_MENU (UUID,ROLEUUID,MENUUUID) values (null,2,'101');
Insert into ERPUSER.ROLE_MENU (UUID,ROLEUUID,MENUUUID) values (null,2,'102');
Insert into ERPUSER.ROLE_MENU (UUID,ROLEUUID,MENUUUID) values (null,2,'103');
Insert into ERPUSER.ROLE_MENU (UUID,ROLEUUID,MENUUUID) values (null,2,'104');
Insert into ERPUSER.ROLE_MENU (UUID,ROLEUUID,MENUUUID) values (null,2,'105');
Insert into ERPUSER.ROLE_MENU (UUID,ROLEUUID,MENUUUID) values (null,2,'200');
Insert into ERPUSER.ROLE_MENU (UUID,ROLEUUID,MENUUUID) values (null,2,'201');
Insert into ERPUSER.ROLE_MENU (UUID,ROLEUUID,MENUUUID) values (null,2,'202');
Insert into ERPUSER.ROLE_MENU (UUID,ROLEUUID,MENUUUID) values (null,2,'300');
Insert into ERPUSER.ROLE_MENU (UUID,ROLEUUID,MENUUUID) values (null,2,'301');
Insert into ERPUSER.ROLE_MENU (UUID,ROLEUUID,MENUUUID) values (null,2,'302');
Insert into ERPUSER.ROLE_MENU (UUID,ROLEUUID,MENUUUID) values (null,2,'303');
Insert into ERPUSER.ROLE_MENU (UUID,ROLEUUID,MENUUUID) values (null,2,'304');
Insert into ERPUSER.ROLE_MENU (UUID,ROLEUUID,MENUUUID) values (null,2,'305');
Insert into ERPUSER.ROLE_MENU (UUID,ROLEUUID,MENUUUID) values (null,2,'306');
Insert into ERPUSER.ROLE_MENU (UUID,ROLEUUID,MENUUUID) values (null,2,'307');
Insert into ERPUSER.ROLE_MENU (UUID,ROLEUUID,MENUUUID) values (null,2,'308');
Insert into ERPUSER.ROLE_MENU (UUID,ROLEUUID,MENUUUID) values (null,2,'309');
Insert into ERPUSER.ROLE_MENU (UUID,ROLEUUID,MENUUUID) values (null,2,'400');
Insert into ERPUSER.ROLE_MENU (UUID,ROLEUUID,MENUUUID) values (null,2,'401');
Insert into ERPUSER.ROLE_MENU (UUID,ROLEUUID,MENUUUID) values (null,2,'402');
Insert into ERPUSER.ROLE_MENU (UUID,ROLEUUID,MENUUUID) values (null,2,'403');
Insert into ERPUSER.ROLE_MENU (UUID,ROLEUUID,MENUUUID) values (null,2,'404');
Insert into ERPUSER.ROLE_MENU (UUID,ROLEUUID,MENUUUID) values (null,2,'405');
Insert into ERPUSER.ROLE_MENU (UUID,ROLEUUID,MENUUUID) values (null,2,'406');
Insert into ERPUSER.ROLE_MENU (UUID,ROLEUUID,MENUUUID) values (null,2,'407');
Insert into ERPUSER.ROLE_MENU (UUID,ROLEUUID,MENUUUID) values (null,2,'500');
Insert into ERPUSER.ROLE_MENU (UUID,ROLEUUID,MENUUUID) values (null,2,'501');
Insert into ERPUSER.ROLE_MENU (UUID,ROLEUUID,MENUUUID) values (null,2,'502');
Insert into ERPUSER.ROLE_MENU (UUID,ROLEUUID,MENUUUID) values (null,2,'503');
Insert into ERPUSER.ROLE_MENU (UUID,ROLEUUID,MENUUUID) values (null,2,'504');
Insert into ERPUSER.ROLE_MENU (UUID,ROLEUUID,MENUUUID) values (null,2,'505');
Insert into ERPUSER.ROLE_MENU (UUID,ROLEUUID,MENUUUID) values (null,2,'506');
Insert into ERPUSER.ROLE_MENU (UUID,ROLEUUID,MENUUUID) values (null,2,'600');
Insert into ERPUSER.ROLE_MENU (UUID,ROLEUUID,MENUUUID) values (null,2,'601');
Insert into ERPUSER.ROLE_MENU (UUID,ROLEUUID,MENUUUID) values (null,2,'602');
Insert into ERPUSER.ROLE_MENU (UUID,ROLEUUID,MENUUUID) values (null,2,'700');
Insert into ERPUSER.ROLE_MENU (UUID,ROLEUUID,MENUUUID) values (null,2,'701');
Insert into ERPUSER.ROLE_MENU (UUID,ROLEUUID,MENUUUID) values (null,2,'702');
Insert into ERPUSER.ROLE_MENU (UUID,ROLEUUID,MENUUUID) values (null,2,'703');
Insert into ERPUSER.ROLE_MENU (UUID,ROLEUUID,MENUUUID) values (null,27,'504');
Insert into ERPUSER.ROLE_MENU (UUID,ROLEUUID,MENUUUID) values (null,27,'505');
Insert into ERPUSER.ROLE_MENU (UUID,ROLEUUID,MENUUUID) values (null,27,'506');
Insert into ERPUSER.ROLE_MENU (UUID,ROLEUUID,MENUUUID) values (null,27,'600');
Insert into ERPUSER.ROLE_MENU (UUID,ROLEUUID,MENUUUID) values (null,27,'601');
Insert into ERPUSER.ROLE_MENU (UUID,ROLEUUID,MENUUUID) values (null,27,'602');
Insert into ERPUSER.ROLE_MENU (UUID,ROLEUUID,MENUUUID) values (null,23,'101');
Insert into ERPUSER.ROLE_MENU (UUID,ROLEUUID,MENUUUID) values (null,23,'102');
Insert into ERPUSER.ROLE_MENU (UUID,ROLEUUID,MENUUUID) values (null,23,'103');
Insert into ERPUSER.ROLE_MENU (UUID,ROLEUUID,MENUUUID) values (null,23,'305');
Insert into ERPUSER.ROLE_MENU (UUID,ROLEUUID,MENUUUID) values (null,23,'309');
Insert into ERPUSER.ROLE_MENU (UUID,ROLEUUID,MENUUUID) values (null,23,'403');
Insert into ERPUSER.ROLE_MENU (UUID,ROLEUUID,MENUUUID) values (null,23,'407');
Insert into ERPUSER.ROLE_MENU (UUID,ROLEUUID,MENUUUID) values (null,23,'501');
Insert into ERPUSER.ROLE_MENU (UUID,ROLEUUID,MENUUUID) values (null,23,'502');
Insert into ERPUSER.ROLE_MENU (UUID,ROLEUUID,MENUUUID) values (null,23,'503');
Insert into ERPUSER.ROLE_MENU (UUID,ROLEUUID,MENUUUID) values (null,23,'505');
Insert into ERPUSER.ROLE_MENU (UUID,ROLEUUID,MENUUUID) values (null,23,'506');
Insert into ERPUSER.ROLE_MENU (UUID,ROLEUUID,MENUUUID) values (null,22,'506');
Insert into ERPUSER.ROLE_MENU (UUID,ROLEUUID,MENUUUID) values (null,24,'101');
Insert into ERPUSER.ROLE_MENU (UUID,ROLEUUID,MENUUUID) values (null,24,'102');
Insert into ERPUSER.ROLE_MENU (UUID,ROLEUUID,MENUUUID) values (null,24,'103');
Insert into ERPUSER.ROLE_MENU (UUID,ROLEUUID,MENUUUID) values (null,24,'104');
Insert into ERPUSER.ROLE_MENU (UUID,ROLEUUID,MENUUUID) values (null,24,'302');
Insert into ERPUSER.ROLE_MENU (UUID,ROLEUUID,MENUUUID) values (null,24,'303');
Insert into ERPUSER.ROLE_MENU (UUID,ROLEUUID,MENUUUID) values (null,24,'304');
Insert into ERPUSER.ROLE_MENU (UUID,ROLEUUID,MENUUUID) values (null,26,'100');
Insert into ERPUSER.ROLE_MENU (UUID,ROLEUUID,MENUUUID) values (null,26,'101');
Insert into ERPUSER.ROLE_MENU (UUID,ROLEUUID,MENUUUID) values (null,26,'102');
Insert into ERPUSER.ROLE_MENU (UUID,ROLEUUID,MENUUUID) values (null,26,'103');
Insert into ERPUSER.ROLE_MENU (UUID,ROLEUUID,MENUUUID) values (null,26,'104');
Insert into ERPUSER.ROLE_MENU (UUID,ROLEUUID,MENUUUID) values (null,26,'105');
Insert into ERPUSER.ROLE_MENU (UUID,ROLEUUID,MENUUUID) values (null,26,'401');
Insert into ERPUSER.ROLE_MENU (UUID,ROLEUUID,MENUUUID) values (null,26,'405');
Insert into ERPUSER.ROLE_MENU (UUID,ROLEUUID,MENUUUID) values (null,26,'406');
Insert into ERPUSER.ROLE_MENU (UUID,ROLEUUID,MENUUUID) values (null,26,'600');
Insert into ERPUSER.ROLE_MENU (UUID,ROLEUUID,MENUUUID) values (null,26,'601');
Insert into ERPUSER.ROLE_MENU (UUID,ROLEUUID,MENUUUID) values (null,26,'602');
Insert into ERPUSER.ROLE_MENU (UUID,ROLEUUID,MENUUUID) values (null,25,'100');
Insert into ERPUSER.ROLE_MENU (UUID,ROLEUUID,MENUUUID) values (null,25,'101');
Insert into ERPUSER.ROLE_MENU (UUID,ROLEUUID,MENUUUID) values (null,25,'102');
Insert into ERPUSER.ROLE_MENU (UUID,ROLEUUID,MENUUUID) values (null,25,'103');
Insert into ERPUSER.ROLE_MENU (UUID,ROLEUUID,MENUUUID) values (null,25,'104');
Insert into ERPUSER.ROLE_MENU (UUID,ROLEUUID,MENUUUID) values (null,25,'105');
Insert into ERPUSER.ROLE_MENU (UUID,ROLEUUID,MENUUUID) values (null,25,'305');
Insert into ERPUSER.ROLE_MENU (UUID,ROLEUUID,MENUUUID) values (null,25,'309');
Insert into ERPUSER.ROLE_MENU (UUID,ROLEUUID,MENUUUID) values (null,25,'403');
Insert into ERPUSER.ROLE_MENU (UUID,ROLEUUID,MENUUUID) values (null,25,'407');
Insert into ERPUSER.ROLE_MENU (UUID,ROLEUUID,MENUUUID) values (null,25,'500');
Insert into ERPUSER.ROLE_MENU (UUID,ROLEUUID,MENUUUID) values (null,25,'501');
Insert into ERPUSER.ROLE_MENU (UUID,ROLEUUID,MENUUUID) values (null,25,'502');
Insert into ERPUSER.ROLE_MENU (UUID,ROLEUUID,MENUUUID) values (null,25,'503');
Insert into ERPUSER.ROLE_MENU (UUID,ROLEUUID,MENUUUID) values (null,25,'504');
Insert into ERPUSER.ROLE_MENU (UUID,ROLEUUID,MENUUUID) values (null,25,'505');
Insert into ERPUSER.ROLE_MENU (UUID,ROLEUUID,MENUUUID) values (null,25,'506');
Insert into ERPUSER.ROLE_MENU (UUID,ROLEUUID,MENUUUID) values (null,24,'307');
Insert into ERPUSER.ROLE_MENU (UUID,ROLEUUID,MENUUUID) values (null,24,'308');

---------------------------------------------------
--   END DATA FOR TABLE ROLE_MENU
---------------------------------------------------

---------------------------------------------------
--   DATA FOR TABLE GOODSTYPE
--   FILTER = none used
---------------------------------------------------
REM INSERTING into ERPUSER.GOODSTYPE
Insert into ERPUSER.GOODSTYPE (UUID,NAME) values (2,'水果');
Insert into ERPUSER.GOODSTYPE (UUID,NAME) values (3,'调味品');
Insert into ERPUSER.GOODSTYPE (UUID,NAME) values (4,'儿童食品');

---------------------------------------------------
--   END DATA FOR TABLE GOODSTYPE
---------------------------------------------------

---------------------------------------------------
--   DATA FOR TABLE STOREDETAIL
--   FILTER = none used
---------------------------------------------------
REM INSERTING into ERPUSER.STOREDETAIL
Insert into ERPUSER.STOREDETAIL (UUID,STOREUUID,GOODSUUID,NUM) values (41,1,41,510);
Insert into ERPUSER.STOREDETAIL (UUID,STOREUUID,GOODSUUID,NUM) values (1,1,5,1499);
Insert into ERPUSER.STOREDETAIL (UUID,STOREUUID,GOODSUUID,NUM) values (2,1,6,1409);
Insert into ERPUSER.STOREDETAIL (UUID,STOREUUID,GOODSUUID,NUM) values (3,1,7,1700);
Insert into ERPUSER.STOREDETAIL (UUID,STOREUUID,GOODSUUID,NUM) values (21,1,21,7900);

---------------------------------------------------
--   END DATA FOR TABLE STOREDETAIL
---------------------------------------------------

---------------------------------------------------
--   DATA FOR TABLE INVENTORY
--   FILTER = none used
---------------------------------------------------
REM INSERTING into ERPUSER.INVENTORY
Insert into ERPUSER.INVENTORY (UUID,GOODSUUID,STOREUUID,NUM,TYPE,CREATETIME,CHECKTIME,CREATER,CHECKER,STATE,REMARK) values (1,6,1,10,'2',to_timestamp('29-Jun -18 02.32.24.865000000 PM','DD-MON-RR HH.MI.SS.FF AM'),to_timestamp('29-Jun -18 03.42.52.431000000 PM','DD-MON-RR HH.MI.SS.FF AM'),8,8,'1','过期');
Insert into ERPUSER.INVENTORY (UUID,GOODSUUID,STOREUUID,NUM,TYPE,CREATETIME,CHECKTIME,CREATER,CHECKER,STATE,REMARK) values (2,7,1,20,'2',to_timestamp('29-Jun -18 03.46.31.098000000 PM','DD-MON-RR HH.MI.SS.FF AM'),null,8,null,'0','包装损坏');

---------------------------------------------------
--   END DATA FOR TABLE INVENTORY
---------------------------------------------------

---------------------------------------------------
--   DATA FOR TABLE ORDERDETAIL
--   FILTER = none used
---------------------------------------------------
REM INSERTING into ERPUSER.ORDERDETAIL
Insert into ERPUSER.ORDERDETAIL (UUID,GOODSUUID,GOODSNAME,PRICE,NUM,MONEY,ENDTIME,ENDER,STOREUUID,STATE,ORDERSUUID) values (45,5,'甜面酱',6.33,200,1266,null,null,null,'0',44);
Insert into ERPUSER.ORDERDETAIL (UUID,GOODSUUID,GOODSNAME,PRICE,NUM,MONEY,ENDTIME,ENDER,STOREUUID,STATE,ORDERSUUID) values (46,7,'好吃点',5.21,200,1042,null,null,null,'0',45);
Insert into ERPUSER.ORDERDETAIL (UUID,GOODSUUID,GOODSNAME,PRICE,NUM,MONEY,ENDTIME,ENDER,STOREUUID,STATE,ORDERSUUID) values (47,21,'香蕉',2.2,400,880,null,null,null,'0',46);
Insert into ERPUSER.ORDERDETAIL (UUID,GOODSUUID,GOODSNAME,PRICE,NUM,MONEY,ENDTIME,ENDER,STOREUUID,STATE,ORDERSUUID) values (48,21,'香蕉',2.2,300,660,null,null,null,'0',47);
Insert into ERPUSER.ORDERDETAIL (UUID,GOODSUUID,GOODSNAME,PRICE,NUM,MONEY,ENDTIME,ENDER,STOREUUID,STATE,ORDERSUUID) values (49,6,'可比克',6.33,100,633,null,null,null,'0',47);
Insert into ERPUSER.ORDERDETAIL (UUID,GOODSUUID,GOODSNAME,PRICE,NUM,MONEY,ENDTIME,ENDER,STOREUUID,STATE,ORDERSUUID) values (50,41,'西瓜',2.5,50,125,null,null,null,'0',48);
Insert into ERPUSER.ORDERDETAIL (UUID,GOODSUUID,GOODSNAME,PRICE,NUM,MONEY,ENDTIME,ENDER,STOREUUID,STATE,ORDERSUUID) values (51,41,'西瓜',1,10,10,to_timestamp('01-Jul -18 01.32.48.164000000 PM','DD-MON-RR HH.MI.SS.FF AM'),8,1,'1',49);
Insert into ERPUSER.ORDERDETAIL (UUID,GOODSUUID,GOODSNAME,PRICE,NUM,MONEY,ENDTIME,ENDER,STOREUUID,STATE,ORDERSUUID) values (61,6,'可比克',3.88,1000,3880,null,null,null,'0',61);
Insert into ERPUSER.ORDERDETAIL (UUID,GOODSUUID,GOODSNAME,PRICE,NUM,MONEY,ENDTIME,ENDER,STOREUUID,STATE,ORDERSUUID) values (62,5,'甜面酱',4.11,1000,4110,null,null,null,'0',61);
Insert into ERPUSER.ORDERDETAIL (UUID,GOODSUUID,GOODSNAME,PRICE,NUM,MONEY,ENDTIME,ENDER,STOREUUID,STATE,ORDERSUUID) values (3,7,'好吃点',4.22,1500,6330,to_timestamp('29-Jun -18 12.32.15.538000000 PM','DD-MON-RR HH.MI.SS.FF AM'),8,1,'1',3);
Insert into ERPUSER.ORDERDETAIL (UUID,GOODSUUID,GOODSNAME,PRICE,NUM,MONEY,ENDTIME,ENDER,STOREUUID,STATE,ORDERSUUID) values (4,5,'甜面酱',4.11,1000,4110,to_timestamp('29-Jun -18 12.32.18.072000000 PM','DD-MON-RR HH.MI.SS.FF AM'),8,1,'1',3);
Insert into ERPUSER.ORDERDETAIL (UUID,GOODSUUID,GOODSNAME,PRICE,NUM,MONEY,ENDTIME,ENDER,STOREUUID,STATE,ORDERSUUID) values (12,7,'好吃点',5.21,600,3126,null,null,null,'0',8);
Insert into ERPUSER.ORDERDETAIL (UUID,GOODSUUID,GOODSNAME,PRICE,NUM,MONEY,ENDTIME,ENDER,STOREUUID,STATE,ORDERSUUID) values (22,21,'香蕉',2.2,1000,2200,to_timestamp('29-Jun -18 11.14.37.183000000 PM','DD-MON-RR HH.MI.SS.FF AM'),8,1,'1',22);
Insert into ERPUSER.ORDERDETAIL (UUID,GOODSUUID,GOODSNAME,PRICE,NUM,MONEY,ENDTIME,ENDER,STOREUUID,STATE,ORDERSUUID) values (23,5,'甜面酱',6.33,200,1266,to_timestamp('29-Jun -18 11.14.40.225000000 PM','DD-MON-RR HH.MI.SS.FF AM'),8,1,'1',22);
Insert into ERPUSER.ORDERDETAIL (UUID,GOODSUUID,GOODSNAME,PRICE,NUM,MONEY,ENDTIME,ENDER,STOREUUID,STATE,ORDERSUUID) values (42,21,'香蕉',2.2,1000,2200,to_timestamp('01-Jul -18 12.39.00.454000000 PM','DD-MON-RR HH.MI.SS.FF AM'),8,1,'1',42);
Insert into ERPUSER.ORDERDETAIL (UUID,GOODSUUID,GOODSNAME,PRICE,NUM,MONEY,ENDTIME,ENDER,STOREUUID,STATE,ORDERSUUID) values (43,5,'甜面酱',6.33,200,1266,to_timestamp('01-Jul -18 12.39.04.984000000 PM','DD-MON-RR HH.MI.SS.FF AM'),8,1,'1',42);
Insert into ERPUSER.ORDERDETAIL (UUID,GOODSUUID,GOODSNAME,PRICE,NUM,MONEY,ENDTIME,ENDER,STOREUUID,STATE,ORDERSUUID) values (5,6,'可比克',6.33,100,633,to_timestamp('28-Jun -18 02.26.55.365000000 PM','DD-MON-RR HH.MI.SS.FF AM'),8,1,'1',4);
Insert into ERPUSER.ORDERDETAIL (UUID,GOODSUUID,GOODSNAME,PRICE,NUM,MONEY,ENDTIME,ENDER,STOREUUID,STATE,ORDERSUUID) values (6,7,'好吃点',5.21,150,781.5,null,null,null,'0',5);
Insert into ERPUSER.ORDERDETAIL (UUID,GOODSUUID,GOODSNAME,PRICE,NUM,MONEY,ENDTIME,ENDER,STOREUUID,STATE,ORDERSUUID) values (7,6,'可比克',3.88,1200,4656,to_timestamp('28-Jun -18 01.57.14.850000000 PM','DD-MON-RR HH.MI.SS.FF AM'),8,1,'1',6);
Insert into ERPUSER.ORDERDETAIL (UUID,GOODSUUID,GOODSNAME,PRICE,NUM,MONEY,ENDTIME,ENDER,STOREUUID,STATE,ORDERSUUID) values (8,7,'好吃点',4.22,500,2110,to_timestamp('28-Jun -18 01.57.18.367000000 PM','DD-MON-RR HH.MI.SS.FF AM'),8,1,'1',6);
Insert into ERPUSER.ORDERDETAIL (UUID,GOODSUUID,GOODSNAME,PRICE,NUM,MONEY,ENDTIME,ENDER,STOREUUID,STATE,ORDERSUUID) values (9,5,'甜面酱',4.11,100,411,null,null,null,'0',7);
Insert into ERPUSER.ORDERDETAIL (UUID,GOODSUUID,GOODSNAME,PRICE,NUM,MONEY,ENDTIME,ENDER,STOREUUID,STATE,ORDERSUUID) values (10,6,'可比克',3.88,100,388,null,null,null,'0',7);
Insert into ERPUSER.ORDERDETAIL (UUID,GOODSUUID,GOODSNAME,PRICE,NUM,MONEY,ENDTIME,ENDER,STOREUUID,STATE,ORDERSUUID) values (11,7,'好吃点',4.22,100,422,null,null,null,'0',7);
Insert into ERPUSER.ORDERDETAIL (UUID,GOODSUUID,GOODSNAME,PRICE,NUM,MONEY,ENDTIME,ENDER,STOREUUID,STATE,ORDERSUUID) values (1,5,'甜面酱',4.11,1000,4110,to_timestamp('26-Jun -18 04.52.19.584000000 PM','DD-MON-RR HH.MI.SS.FF AM'),8,1,'1',2);
Insert into ERPUSER.ORDERDETAIL (UUID,GOODSUUID,GOODSNAME,PRICE,NUM,MONEY,ENDTIME,ENDER,STOREUUID,STATE,ORDERSUUID) values (2,6,'可比克',3.88,1000,3880,to_timestamp('26-Jun -18 04.52.35.307000000 PM','DD-MON-RR HH.MI.SS.FF AM'),8,1,'1',2);
Insert into ERPUSER.ORDERDETAIL (UUID,GOODSUUID,GOODSNAME,PRICE,NUM,MONEY,ENDTIME,ENDER,STOREUUID,STATE,ORDERSUUID) values (21,21,'香蕉',1.2,10000,12000,to_timestamp('29-Jun -18 11.13.58.513000000 PM','DD-MON-RR HH.MI.SS.FF AM'),8,1,'1',21);
Insert into ERPUSER.ORDERDETAIL (UUID,GOODSUUID,GOODSNAME,PRICE,NUM,MONEY,ENDTIME,ENDER,STOREUUID,STATE,ORDERSUUID) values (41,21,'香蕉',2.2,100,220,to_timestamp('01-Jul -18 12.30.42.037000000 PM','DD-MON-RR HH.MI.SS.FF AM'),8,1,'1',41);
Insert into ERPUSER.ORDERDETAIL (UUID,GOODSUUID,GOODSNAME,PRICE,NUM,MONEY,ENDTIME,ENDER,STOREUUID,STATE,ORDERSUUID) values (44,7,'好吃点',5.21,300,1563,to_timestamp('01-Jul -18 12.39.47.958000000 PM','DD-MON-RR HH.MI.SS.FF AM'),8,1,'1',43);
Insert into ERPUSER.ORDERDETAIL (UUID,GOODSUUID,GOODSNAME,PRICE,NUM,MONEY,ENDTIME,ENDER,STOREUUID,STATE,ORDERSUUID) values (52,41,'西瓜',1,500,500,to_timestamp('01-Jul -18 03.08.34.857000000 PM','DD-MON-RR HH.MI.SS.FF AM'),8,1,'1',50);

---------------------------------------------------
--   END DATA FOR TABLE ORDERDETAIL
---------------------------------------------------

---------------------------------------------------
--   DATA FOR TABLE STORE
--   FILTER = none used
---------------------------------------------------
REM INSERTING into ERPUSER.STORE
Insert into ERPUSER.STORE (UUID,NAME,EMPUUID) values (1,'食品',8);

---------------------------------------------------
--   END DATA FOR TABLE STORE
---------------------------------------------------

---------------------------------------------------
--   DATA FOR TABLE EMP
--   FILTER = none used
---------------------------------------------------
REM INSERTING into ERPUSER.EMP
Insert into ERPUSER.EMP (UUID,USERNAME,PWD,NAME,GENDER,EMAIL,TELE,ADDRESS,BIRTHDAY,DEPUUID) values (3,'sunwukong','6524c338727928082b70e8c8843f9d7a','孙悟空',1,'swk@itcast.cn','12345678','花果山水帘洞11-2',to_timestamp('01-Oct-49 12.00.00.000000000 AM','DD-MON-RR HH.MI.SS.FF AM'),2);
Insert into ERPUSER.EMP (UUID,USERNAME,PWD,NAME,GENDER,EMAIL,TELE,ADDRESS,BIRTHDAY,DEPUUID) values (4,'tangseng','e4f15a4bdc645430f2f9f17689322645','唐僧',0,'ts@itcast.cn','12345678','东土大唐小区90-14',to_timestamp('01-Oct-49 12.00.00.000000000 AM','DD-MON-RR HH.MI.SS.FF AM'),2);
Insert into ERPUSER.EMP (UUID,USERNAME,PWD,NAME,GENDER,EMAIL,TELE,ADDRESS,BIRTHDAY,DEPUUID) values (5,'zhubajie','8db8079baa52ac45c67303cf70131360','猪八戒',1,'zbj@itcast.cn','12345678','高老庄生态园2-3',to_timestamp('01-Oct-49 12.00.00.000000000 AM','DD-MON-RR HH.MI.SS.FF AM'),3);
Insert into ERPUSER.EMP (UUID,USERNAME,PWD,NAME,GENDER,EMAIL,TELE,ADDRESS,BIRTHDAY,DEPUUID) values (6,'shaheshang','69e19cb9bd43c60a71c0351452049f48','沙和尚',1,'shs@itcast.cn','12345678','流沙河风景区4-4',to_timestamp('01-Oct-49 12.00.00.000000000 AM','DD-MON-RR HH.MI.SS.FF AM'),3);
Insert into ERPUSER.EMP (UUID,USERNAME,PWD,NAME,GENDER,EMAIL,TELE,ADDRESS,BIRTHDAY,DEPUUID) values (7,'bailongma','90c46ce2866f2effb3db1ad34724327d','白龙马',1,'blm@itcast.cn','12345678','西海家园4-9-1',to_timestamp('01-Oct-49 12.00.00.000000000 AM','DD-MON-RR HH.MI.SS.FF AM'),16);
Insert into ERPUSER.EMP (UUID,USERNAME,PWD,NAME,GENDER,EMAIL,TELE,ADDRESS,BIRTHDAY,DEPUUID) values (8,'admin','928bfd2577490322a6e19b793691467e','超级管理员',1,'admin@qq.com','12345678','西海家园4-9-1',to_timestamp('01-Oct-49 12.00.00.000000000 AM','DD-MON-RR HH.MI.SS.FF AM'),2);

---------------------------------------------------
--   END DATA FOR TABLE EMP
---------------------------------------------------

---------------------------------------------------
--   DATA FOR TABLE MENU
--   FILTER = none used
---------------------------------------------------
REM INSERTING into ERPUSER.MENU
Insert into ERPUSER.MENU (MENUID,MENUNAME,ICON,URL,PID) values ('0','系统菜单','icon-sys',null,null);
Insert into ERPUSER.MENU (MENUID,MENUNAME,ICON,URL,PID) values ('100','基础数据','icon-sys',null,'0');
Insert into ERPUSER.MENU (MENUID,MENUNAME,ICON,URL,PID) values ('101','商品类型','icon-sys','goodstype.html','100');
Insert into ERPUSER.MENU (MENUID,MENUNAME,ICON,URL,PID) values ('102','商品','icon-sys','goods.html','100');
Insert into ERPUSER.MENU (MENUID,MENUNAME,ICON,URL,PID) values ('103','仓库','icon-sys','store.html','100');
Insert into ERPUSER.MENU (MENUID,MENUNAME,ICON,URL,PID) values ('200','人事管理','icon-sys',null,'0');
Insert into ERPUSER.MENU (MENUID,MENUNAME,ICON,URL,PID) values ('201','部门','icon-sys','dep.html','200');
Insert into ERPUSER.MENU (MENUID,MENUNAME,ICON,URL,PID) values ('202','员工','icon-sys','emp.html','200');
Insert into ERPUSER.MENU (MENUID,MENUNAME,ICON,URL,PID) values ('104','供应商管理','icon-sys','supplier.html?type=1','100');
Insert into ERPUSER.MENU (MENUID,MENUNAME,ICON,URL,PID) values ('105','客户管理','icon-sys','supplier.html?type=2','100');
Insert into ERPUSER.MENU (MENUID,MENUNAME,ICON,URL,PID) values ('300','采购管理','icon-sys',null,'0');
Insert into ERPUSER.MENU (MENUID,MENUNAME,ICON,URL,PID) values ('301','采购申请','icon-sys','orders.html?oper=myOrders&type=1','300');
Insert into ERPUSER.MENU (MENUID,MENUNAME,ICON,URL,PID) values ('302','采购订单查询','icon-sys','orders.html?oper=orders&type=1','300');
Insert into ERPUSER.MENU (MENUID,MENUNAME,ICON,URL,PID) values ('303','采购订单审核','icon-sys','orders.html?oper=doCheck&type=1','300');
Insert into ERPUSER.MENU (MENUID,MENUNAME,ICON,URL,PID) values ('304','采购订单确认','icon-sys','orders.html?oper=doStart&type=1','300');
Insert into ERPUSER.MENU (MENUID,MENUNAME,ICON,URL,PID) values ('305','采购订单入库','icon-sys','orders.html?oper=doInStore&type=1','300');
Insert into ERPUSER.MENU (MENUID,MENUNAME,ICON,URL,PID) values ('400','销售管理','icon-sys',null,'0');
Insert into ERPUSER.MENU (MENUID,MENUNAME,ICON,URL,PID) values ('401','销售订单查询','icon-sys','orders.html?oper=orders&type=2','400');
Insert into ERPUSER.MENU (MENUID,MENUNAME,ICON,URL,PID) values ('402','销售订单录入','icon-sys','orders.html?oper=myOrders&type=2','400');
Insert into ERPUSER.MENU (MENUID,MENUNAME,ICON,URL,PID) values ('403','销售订单出库','icon-sys','orders.html?oper=doOutStore&type=2','400');
Insert into ERPUSER.MENU (MENUID,MENUNAME,ICON,URL,PID) values ('500','库存管理 ','icon-sys',null,'0');
Insert into ERPUSER.MENU (MENUID,MENUNAME,ICON,URL,PID) values ('501','库存查询','icon-sys','storedetail.html','500');
Insert into ERPUSER.MENU (MENUID,MENUNAME,ICON,URL,PID) values ('306','退货订单登记','icon-sys','returnorders.html?oper=myOrders','300');
Insert into ERPUSER.MENU (MENUID,MENUNAME,ICON,URL,PID) values ('307','退货订单查询','icon-sys','returnorders.html?oper=orders','300');
Insert into ERPUSER.MENU (MENUID,MENUNAME,ICON,URL,PID) values ('308','退货订单审核','icon-sys','returnorders.html?oper=doCheck','300');
Insert into ERPUSER.MENU (MENUID,MENUNAME,ICON,URL,PID) values ('309','退货订单出库','icon-sys','returnorders.html?oper=doOutStore','300');
Insert into ERPUSER.MENU (MENUID,MENUNAME,ICON,URL,PID) values ('502','库存变动记录','icon-sys','storeoper.html','500');
Insert into ERPUSER.MENU (MENUID,MENUNAME,ICON,URL,PID) values ('700','权限管理','icon-sys',null,'0');
Insert into ERPUSER.MENU (MENUID,MENUNAME,ICON,URL,PID) values ('701','重置密码','icon-sys','pwd.html','700');
Insert into ERPUSER.MENU (MENUID,MENUNAME,ICON,URL,PID) values ('600','统计分析','icon-sys',null,'0');
Insert into ERPUSER.MENU (MENUID,MENUNAME,ICON,URL,PID) values ('404','销售退货登记','icon-sys','returnorders1.html?oper=myOrders','400');
Insert into ERPUSER.MENU (MENUID,MENUNAME,ICON,URL,PID) values ('405','销售退货查询','icon-sys','returnorders1.html?oper=orders','400');
Insert into ERPUSER.MENU (MENUID,MENUNAME,ICON,URL,PID) values ('406','销售退货审核','icon-sys','returnorders1.html?oper=doCheck','400');
Insert into ERPUSER.MENU (MENUID,MENUNAME,ICON,URL,PID) values ('407','销售退货入库','icon-sys','returnorders1.html?oper=doInStore','400');
Insert into ERPUSER.MENU (MENUID,MENUNAME,ICON,URL,PID) values ('503','盘盈盘亏登记','icon-sys','inventory.html?oper=inventory','500');
Insert into ERPUSER.MENU (MENUID,MENUNAME,ICON,URL,PID) values ('504','盘盈盘亏审核','icon-sys','inventory.html?oper=doCheck','500');
Insert into ERPUSER.MENU (MENUID,MENUNAME,ICON,URL,PID) values ('505','盘盈盘亏查询','icon-sys','inventory.html?oper=search','500');
Insert into ERPUSER.MENU (MENUID,MENUNAME,ICON,URL,PID) values ('601','销售统计表','icon-sys','report_order.html','600');
Insert into ERPUSER.MENU (MENUID,MENUNAME,ICON,URL,PID) values ('602','销售趋势分析','icon-sys','report_trend.html','600');
Insert into ERPUSER.MENU (MENUID,MENUNAME,ICON,URL,PID) values ('506','库存预警','icon-sys','storealert.html','500');
Insert into ERPUSER.MENU (MENUID,MENUNAME,ICON,URL,PID) values ('702','角色管理','icon-sys','role.html','700');
Insert into ERPUSER.MENU (MENUID,MENUNAME,ICON,URL,PID) values ('703','员工角色设置','icon-sys','emp_roleSet.html','700');
Insert into ERPUSER.MENU (MENUID,MENUNAME,ICON,URL,PID) values ('704','角色权限设置','icon-sys','role_menuSet.html','700');

---------------------------------------------------
--   END DATA FOR TABLE MENU
---------------------------------------------------

---------------------------------------------------
--   DATA FOR TABLE STOREOPER
--   FILTER = none used
---------------------------------------------------
REM INSERTING into ERPUSER.STOREOPER
Insert into ERPUSER.STOREOPER (UUID,EMPUUID,OPERTIME,STOREUUID,GOODSUUID,NUM,TYPE) values (10,8,to_timestamp('29-Jun -18 12.05.42.243000000 AM','DD-MON-RR HH.MI.SS.FF AM'),1,5,100,'1');
Insert into ERPUSER.STOREOPER (UUID,EMPUUID,OPERTIME,STOREUUID,GOODSUUID,NUM,TYPE) values (11,8,to_timestamp('29-Jun -18 12.07.00.583000000 AM','DD-MON-RR HH.MI.SS.FF AM'),1,6,500,'1');
Insert into ERPUSER.STOREOPER (UUID,EMPUUID,OPERTIME,STOREUUID,GOODSUUID,NUM,TYPE) values (45,8,to_timestamp('01-Jul -18 01.32.48.164000000 PM','DD-MON-RR HH.MI.SS.FF AM'),1,41,10,'0');
Insert into ERPUSER.STOREOPER (UUID,EMPUUID,OPERTIME,STOREUUID,GOODSUUID,NUM,TYPE) values (1,8,to_timestamp('26-Jun -18 04.52.19.584000000 PM','DD-MON-RR HH.MI.SS.FF AM'),1,5,1000,'0');
Insert into ERPUSER.STOREOPER (UUID,EMPUUID,OPERTIME,STOREUUID,GOODSUUID,NUM,TYPE) values (2,8,to_timestamp('26-Jun -18 04.52.35.307000000 PM','DD-MON-RR HH.MI.SS.FF AM'),1,6,1000,'0');
Insert into ERPUSER.STOREOPER (UUID,EMPUUID,OPERTIME,STOREUUID,GOODSUUID,NUM,TYPE) values (3,8,to_timestamp('28-Jun -18 01.57.14.850000000 PM','DD-MON-RR HH.MI.SS.FF AM'),1,6,1200,'0');
Insert into ERPUSER.STOREOPER (UUID,EMPUUID,OPERTIME,STOREUUID,GOODSUUID,NUM,TYPE) values (4,8,to_timestamp('28-Jun -18 01.57.18.367000000 PM','DD-MON-RR HH.MI.SS.FF AM'),1,7,500,'0');
Insert into ERPUSER.STOREOPER (UUID,EMPUUID,OPERTIME,STOREUUID,GOODSUUID,NUM,TYPE) values (9,8,to_timestamp('28-Jun -18 02.26.55.365000000 PM','DD-MON-RR HH.MI.SS.FF AM'),1,6,100,'1');
Insert into ERPUSER.STOREOPER (UUID,EMPUUID,OPERTIME,STOREUUID,GOODSUUID,NUM,TYPE) values (12,8,to_timestamp('29-Jun -18 11.14.47.410000000 AM','DD-MON-RR HH.MI.SS.FF AM'),1,5,1,'1');
Insert into ERPUSER.STOREOPER (UUID,EMPUUID,OPERTIME,STOREUUID,GOODSUUID,NUM,TYPE) values (13,8,to_timestamp('29-Jun -18 12.23.33.954000000 PM','DD-MON-RR HH.MI.SS.FF AM'),1,6,200,'1');
Insert into ERPUSER.STOREOPER (UUID,EMPUUID,OPERTIME,STOREUUID,GOODSUUID,NUM,TYPE) values (14,8,to_timestamp('29-Jun -18 12.32.15.538000000 PM','DD-MON-RR HH.MI.SS.FF AM'),1,7,1500,'0');
Insert into ERPUSER.STOREOPER (UUID,EMPUUID,OPERTIME,STOREUUID,GOODSUUID,NUM,TYPE) values (15,8,to_timestamp('29-Jun -18 12.32.18.072000000 PM','DD-MON-RR HH.MI.SS.FF AM'),1,5,1000,'0');
Insert into ERPUSER.STOREOPER (UUID,EMPUUID,OPERTIME,STOREUUID,GOODSUUID,NUM,TYPE) values (16,8,to_timestamp('29-Jun -18 01.18.01.529000000 PM','DD-MON-RR HH.MI.SS.FF AM'),1,6,19,'0');
Insert into ERPUSER.STOREOPER (UUID,EMPUUID,OPERTIME,STOREUUID,GOODSUUID,NUM,TYPE) values (17,8,to_timestamp('29-Jun -18 03.42.52.431000000 PM','DD-MON-RR HH.MI.SS.FF AM'),1,6,10,'3');
Insert into ERPUSER.STOREOPER (UUID,EMPUUID,OPERTIME,STOREUUID,GOODSUUID,NUM,TYPE) values (41,8,to_timestamp('01-Jul -18 12.30.42.037000000 PM','DD-MON-RR HH.MI.SS.FF AM'),1,21,100,'1');
Insert into ERPUSER.STOREOPER (UUID,EMPUUID,OPERTIME,STOREUUID,GOODSUUID,NUM,TYPE) values (44,8,to_timestamp('01-Jul -18 12.39.47.958000000 PM','DD-MON-RR HH.MI.SS.FF AM'),1,7,300,'1');
Insert into ERPUSER.STOREOPER (UUID,EMPUUID,OPERTIME,STOREUUID,GOODSUUID,NUM,TYPE) values (21,8,to_timestamp('29-Jun -18 11.13.58.513000000 PM','DD-MON-RR HH.MI.SS.FF AM'),1,21,10000,'0');
Insert into ERPUSER.STOREOPER (UUID,EMPUUID,OPERTIME,STOREUUID,GOODSUUID,NUM,TYPE) values (22,8,to_timestamp('29-Jun -18 11.14.37.183000000 PM','DD-MON-RR HH.MI.SS.FF AM'),1,21,1000,'1');
Insert into ERPUSER.STOREOPER (UUID,EMPUUID,OPERTIME,STOREUUID,GOODSUUID,NUM,TYPE) values (23,8,to_timestamp('29-Jun -18 11.14.40.225000000 PM','DD-MON-RR HH.MI.SS.FF AM'),1,5,200,'1');
Insert into ERPUSER.STOREOPER (UUID,EMPUUID,OPERTIME,STOREUUID,GOODSUUID,NUM,TYPE) values (42,8,to_timestamp('01-Jul -18 12.39.00.454000000 PM','DD-MON-RR HH.MI.SS.FF AM'),1,21,1000,'1');
Insert into ERPUSER.STOREOPER (UUID,EMPUUID,OPERTIME,STOREUUID,GOODSUUID,NUM,TYPE) values (43,8,to_timestamp('01-Jul -18 12.39.04.984000000 PM','DD-MON-RR HH.MI.SS.FF AM'),1,5,200,'1');
Insert into ERPUSER.STOREOPER (UUID,EMPUUID,OPERTIME,STOREUUID,GOODSUUID,NUM,TYPE) values (46,8,to_timestamp('01-Jul -18 03.08.34.857000000 PM','DD-MON-RR HH.MI.SS.FF AM'),1,41,500,'0');

---------------------------------------------------
--   END DATA FOR TABLE STOREOPER
---------------------------------------------------

---------------------------------------------------
--   DATA FOR TABLE ORDERS
--   FILTER = none used
---------------------------------------------------
REM INSERTING into ERPUSER.ORDERS
Insert into ERPUSER.ORDERS (UUID,CREATETIME,CHECKTIME,STARTTIME,ENDTIME,TYPE,CREATER,CHECKER,STARTER,ENDER,SUPPLIERUUID,TOTALMONEY,STATE,WAYBILLSN) values (44,to_timestamp('01-Sep -18 12.56.54.232000000 PM','DD-MON-RR HH.MI.SS.FF AM'),null,null,null,'2',8,null,null,null,2,1266,'0',null);
Insert into ERPUSER.ORDERS (UUID,CREATETIME,CHECKTIME,STARTTIME,ENDTIME,TYPE,CREATER,CHECKER,STARTER,ENDER,SUPPLIERUUID,TOTALMONEY,STATE,WAYBILLSN) values (45,to_timestamp('01-Aug -18 12.57.05.855000000 PM','DD-MON-RR HH.MI.SS.FF AM'),null,null,null,'2',8,null,null,null,2,1042,'0',null);
Insert into ERPUSER.ORDERS (UUID,CREATETIME,CHECKTIME,STARTTIME,ENDTIME,TYPE,CREATER,CHECKER,STARTER,ENDER,SUPPLIERUUID,TOTALMONEY,STATE,WAYBILLSN) values (46,to_timestamp('01-Oct-18 12.57.48.993000000 PM','DD-MON-RR HH.MI.SS.FF AM'),null,null,null,'2',8,null,null,null,2,880,'0',null);
Insert into ERPUSER.ORDERS (UUID,CREATETIME,CHECKTIME,STARTTIME,ENDTIME,TYPE,CREATER,CHECKER,STARTER,ENDER,SUPPLIERUUID,TOTALMONEY,STATE,WAYBILLSN) values (47,to_timestamp('01-Nov-18 12.59.56.475000000 PM','DD-MON-RR HH.MI.SS.FF AM'),null,null,null,'2',8,null,null,null,2,1293,'0',null);
Insert into ERPUSER.ORDERS (UUID,CREATETIME,CHECKTIME,STARTTIME,ENDTIME,TYPE,CREATER,CHECKER,STARTER,ENDER,SUPPLIERUUID,TOTALMONEY,STATE,WAYBILLSN) values (48,to_timestamp('01-Jul -18 01.30.43.697000000 PM','DD-MON-RR HH.MI.SS.FF AM'),null,null,null,'2',8,null,null,null,2,125,'0',null);
Insert into ERPUSER.ORDERS (UUID,CREATETIME,CHECKTIME,STARTTIME,ENDTIME,TYPE,CREATER,CHECKER,STARTER,ENDER,SUPPLIERUUID,TOTALMONEY,STATE,WAYBILLSN) values (49,to_timestamp('01-Jul -18 01.32.29.367000000 PM','DD-MON-RR HH.MI.SS.FF AM'),to_timestamp('01-Jul -18 01.32.37.040000000 PM','DD-MON-RR HH.MI.SS.FF AM'),to_timestamp('01-Jul -18 01.32.41.800000000 PM','DD-MON-RR HH.MI.SS.FF AM'),to_timestamp('01-Jul -18 01.32.48.164000000 PM','DD-MON-RR HH.MI.SS.FF AM'),'1',8,8,8,8,1,10,'3',null);
Insert into ERPUSER.ORDERS (UUID,CREATETIME,CHECKTIME,STARTTIME,ENDTIME,TYPE,CREATER,CHECKER,STARTER,ENDER,SUPPLIERUUID,TOTALMONEY,STATE,WAYBILLSN) values (61,to_timestamp('14-Jul -18 05.00.46.759000000 PM','DD-MON-RR HH.MI.SS.FF AM'),to_timestamp('05-Jul -18 08.28.49.878000000 AM','DD-MON-RR HH.MI.SS.FF AM'),null,null,'1',8,8,null,null,1,7990,'1',null);
Insert into ERPUSER.ORDERS (UUID,CREATETIME,CHECKTIME,STARTTIME,ENDTIME,TYPE,CREATER,CHECKER,STARTER,ENDER,SUPPLIERUUID,TOTALMONEY,STATE,WAYBILLSN) values (8,to_timestamp('28-May -18 02.30.38.528000000 PM','DD-MON-RR HH.MI.SS.FF AM'),null,null,null,'2',8,null,null,null,2,3126,'0',null);
Insert into ERPUSER.ORDERS (UUID,CREATETIME,CHECKTIME,STARTTIME,ENDTIME,TYPE,CREATER,CHECKER,STARTER,ENDER,SUPPLIERUUID,TOTALMONEY,STATE,WAYBILLSN) values (3,to_timestamp('26-Jun -18 09.15.37.932000000 PM','DD-MON-RR HH.MI.SS.FF AM'),to_timestamp('28-Jun -18 12.56.55.108000000 PM','DD-MON-RR HH.MI.SS.FF AM'),to_timestamp('28-Jun -18 02.00.39.829000000 PM','DD-MON-RR HH.MI.SS.FF AM'),to_timestamp('29-Jun -18 12.32.18.072000000 PM','DD-MON-RR HH.MI.SS.FF AM'),'1',8,8,8,8,1,10440,'3',null);
Insert into ERPUSER.ORDERS (UUID,CREATETIME,CHECKTIME,STARTTIME,ENDTIME,TYPE,CREATER,CHECKER,STARTER,ENDER,SUPPLIERUUID,TOTALMONEY,STATE,WAYBILLSN) values (22,to_timestamp('28-Feb -18 11.14.28.693000000 PM','DD-MON-RR HH.MI.SS.FF AM'),null,null,to_timestamp('29-Jun -18 11.14.40.225000000 PM','DD-MON-RR HH.MI.SS.FF AM'),'2',8,null,null,8,2,3466,'1',null);
Insert into ERPUSER.ORDERS (UUID,CREATETIME,CHECKTIME,STARTTIME,ENDTIME,TYPE,CREATER,CHECKER,STARTER,ENDER,SUPPLIERUUID,TOTALMONEY,STATE,WAYBILLSN) values (42,to_timestamp('01-Jul -18 12.38.41.203000000 PM','DD-MON-RR HH.MI.SS.FF AM'),null,null,to_timestamp('01-Jul -18 12.39.04.984000000 PM','DD-MON-RR HH.MI.SS.FF AM'),'2',8,null,null,8,2,3466,'1',null);
Insert into ERPUSER.ORDERS (UUID,CREATETIME,CHECKTIME,STARTTIME,ENDTIME,TYPE,CREATER,CHECKER,STARTER,ENDER,SUPPLIERUUID,TOTALMONEY,STATE,WAYBILLSN) values (4,to_timestamp('26-Apr -18 10.08.27.103000000 PM','DD-MON-RR HH.MI.SS.FF AM'),null,null,to_timestamp('28-Jun -18 02.26.55.365000000 PM','DD-MON-RR HH.MI.SS.FF AM'),'2',8,null,null,8,2,633,'1',null);
Insert into ERPUSER.ORDERS (UUID,CREATETIME,CHECKTIME,STARTTIME,ENDTIME,TYPE,CREATER,CHECKER,STARTER,ENDER,SUPPLIERUUID,TOTALMONEY,STATE,WAYBILLSN) values (5,to_timestamp('26-Mar -18 10.11.18.903000000 PM','DD-MON-RR HH.MI.SS.FF AM'),null,null,null,'2',8,null,null,null,2,781.5,'0',null);
Insert into ERPUSER.ORDERS (UUID,CREATETIME,CHECKTIME,STARTTIME,ENDTIME,TYPE,CREATER,CHECKER,STARTER,ENDER,SUPPLIERUUID,TOTALMONEY,STATE,WAYBILLSN) values (6,to_timestamp('26-Jun -18 10.14.39.641000000 PM','DD-MON-RR HH.MI.SS.FF AM'),to_timestamp('28-Jun -18 01.49.11.526000000 PM','DD-MON-RR HH.MI.SS.FF AM'),to_timestamp('28-Jun -18 01.49.23.435000000 PM','DD-MON-RR HH.MI.SS.FF AM'),to_timestamp('28-Jun -18 01.57.18.367000000 PM','DD-MON-RR HH.MI.SS.FF AM'),'1',8,8,8,8,1,6766,'3',null);
Insert into ERPUSER.ORDERS (UUID,CREATETIME,CHECKTIME,STARTTIME,ENDTIME,TYPE,CREATER,CHECKER,STARTER,ENDER,SUPPLIERUUID,TOTALMONEY,STATE,WAYBILLSN) values (7,to_timestamp('26-Jun -18 10.18.23.151000000 PM','DD-MON-RR HH.MI.SS.FF AM'),null,null,null,'1',8,null,null,null,1,1221,'0',null);
Insert into ERPUSER.ORDERS (UUID,CREATETIME,CHECKTIME,STARTTIME,ENDTIME,TYPE,CREATER,CHECKER,STARTER,ENDER,SUPPLIERUUID,TOTALMONEY,STATE,WAYBILLSN) values (2,to_timestamp('24-Jun -18 01.49.22.044000000 PM','DD-MON-RR HH.MI.SS.FF AM'),to_timestamp('25-Jun -18 06.30.01.139000000 PM','DD-MON-RR HH.MI.SS.FF AM'),to_timestamp('25-Jun -18 06.30.08.994000000 PM','DD-MON-RR HH.MI.SS.FF AM'),to_timestamp('26-Jun -18 04.52.35.307000000 PM','DD-MON-RR HH.MI.SS.FF AM'),'1',8,8,8,8,1,7990,'3',null);
Insert into ERPUSER.ORDERS (UUID,CREATETIME,CHECKTIME,STARTTIME,ENDTIME,TYPE,CREATER,CHECKER,STARTER,ENDER,SUPPLIERUUID,TOTALMONEY,STATE,WAYBILLSN) values (21,to_timestamp('29-Jun -18 11.13.38.074000000 PM','DD-MON-RR HH.MI.SS.FF AM'),to_timestamp('29-Jun -18 11.13.46.312000000 PM','DD-MON-RR HH.MI.SS.FF AM'),to_timestamp('29-Jun -18 11.13.52.077000000 PM','DD-MON-RR HH.MI.SS.FF AM'),to_timestamp('29-Jun -18 11.13.58.513000000 PM','DD-MON-RR HH.MI.SS.FF AM'),'1',8,8,8,8,1,12000,'3',null);
Insert into ERPUSER.ORDERS (UUID,CREATETIME,CHECKTIME,STARTTIME,ENDTIME,TYPE,CREATER,CHECKER,STARTER,ENDER,SUPPLIERUUID,TOTALMONEY,STATE,WAYBILLSN) values (41,to_timestamp('01-Jun -18 12.30.21.569000000 PM','DD-MON-RR HH.MI.SS.FF AM'),null,null,to_timestamp('01-Jul -18 12.30.42.037000000 PM','DD-MON-RR HH.MI.SS.FF AM'),'2',8,null,null,8,2,220,'1',null);
Insert into ERPUSER.ORDERS (UUID,CREATETIME,CHECKTIME,STARTTIME,ENDTIME,TYPE,CREATER,CHECKER,STARTER,ENDER,SUPPLIERUUID,TOTALMONEY,STATE,WAYBILLSN) values (43,to_timestamp('01-Jan -18 12.39.36.747000000 PM','DD-MON-RR HH.MI.SS.FF AM'),null,null,to_timestamp('01-Jul -18 12.39.47.958000000 PM','DD-MON-RR HH.MI.SS.FF AM'),'2',8,null,null,8,2,1563,'1',null);
Insert into ERPUSER.ORDERS (UUID,CREATETIME,CHECKTIME,STARTTIME,ENDTIME,TYPE,CREATER,CHECKER,STARTER,ENDER,SUPPLIERUUID,TOTALMONEY,STATE,WAYBILLSN) values (50,to_timestamp('01-Jul -18 03.08.17.068000000 PM','DD-MON-RR HH.MI.SS.FF AM'),to_timestamp('01-Jul -18 03.08.23.245000000 PM','DD-MON-RR HH.MI.SS.FF AM'),to_timestamp('01-Jul -18 03.08.27.693000000 PM','DD-MON-RR HH.MI.SS.FF AM'),to_timestamp('01-Jul -18 03.08.34.857000000 PM','DD-MON-RR HH.MI.SS.FF AM'),'1',8,8,8,8,1,500,'3',null);

---------------------------------------------------
--   END DATA FOR TABLE ORDERS
---------------------------------------------------

---------------------------------------------------
--   DATA FOR TABLE SUPPLIER
--   FILTER = none used
---------------------------------------------------
REM INSERTING into ERPUSER.SUPPLIER
Insert into ERPUSER.SUPPLIER (UUID,NAME,ADDRESS,CONTACT,TELE,EMAIL,TYPE) values (1,'马云','浙江杭州','马云','1231545','mayun@taobao.com','1');
Insert into ERPUSER.SUPPLIER (UUID,NAME,ADDRESS,CONTACT,TELE,EMAIL,TYPE) values (2,'徐帅','内江师范学院','徐帅','123154','xushuai@163.com','2');

---------------------------------------------------
--   END DATA FOR TABLE SUPPLIER
---------------------------------------------------

---------------------------------------------------
--   DATA FOR TABLE RETURNORDERS
--   FILTER = none used
---------------------------------------------------
REM INSERTING into ERPUSER.RETURNORDERS
Insert into ERPUSER.RETURNORDERS (UUID,CREATETIME,CHECKTIME,ENDTIME,TYPE,CREATER,CHECKER,ENDER,SUPPLIERUUID,TOTALMONEY,STATE,WAYBILLSN,ORDERSUUID) values (1,to_timestamp('28-Jun -18 09.28.25.565000000 PM','DD-MON-RR HH.MI.SS.FF AM'),to_timestamp('28-Jun -18 09.28.25.565000000 PM','DD-MON-RR HH.MI.SS.FF AM'),to_timestamp('29-Jun -18 12.07.00.583000000 AM','DD-MON-RR HH.MI.SS.FF AM'),'1',8,8,8,1,2351,'2',null,null);
Insert into ERPUSER.RETURNORDERS (UUID,CREATETIME,CHECKTIME,ENDTIME,TYPE,CREATER,CHECKER,ENDER,SUPPLIERUUID,TOTALMONEY,STATE,WAYBILLSN,ORDERSUUID) values (2,to_timestamp('29-Jun -18 10.57.43.729000000 AM','DD-MON-RR HH.MI.SS.FF AM'),to_timestamp('29-Jun -18 12.23.14.540000000 PM','DD-MON-RR HH.MI.SS.FF AM'),to_timestamp('29-Jun -18 12.23.33.954000000 PM','DD-MON-RR HH.MI.SS.FF AM'),'1',8,8,8,1,776,'2',null,null);
Insert into ERPUSER.RETURNORDERS (UUID,CREATETIME,CHECKTIME,ENDTIME,TYPE,CREATER,CHECKER,ENDER,SUPPLIERUUID,TOTALMONEY,STATE,WAYBILLSN,ORDERSUUID) values (3,to_timestamp('29-Jun -18 11.09.13.932000000 AM','DD-MON-RR HH.MI.SS.FF AM'),to_timestamp('29-Jun -18 11.14.33.754000000 AM','DD-MON-RR HH.MI.SS.FF AM'),to_timestamp('29-Jun -18 11.14.47.410000000 AM','DD-MON-RR HH.MI.SS.FF AM'),'1',8,8,8,1,4.11,'2',null,null);
Insert into ERPUSER.RETURNORDERS (UUID,CREATETIME,CHECKTIME,ENDTIME,TYPE,CREATER,CHECKER,ENDER,SUPPLIERUUID,TOTALMONEY,STATE,WAYBILLSN,ORDERSUUID) values (22,to_timestamp('17-Aug -18 02.55.01.392000000 AM','DD-MON-RR HH.MI.SS.FF AM'),null,null,'2',8,null,null,2,12.66,'0',null,null);
Insert into ERPUSER.RETURNORDERS (UUID,CREATETIME,CHECKTIME,ENDTIME,TYPE,CREATER,CHECKER,ENDER,SUPPLIERUUID,TOTALMONEY,STATE,WAYBILLSN,ORDERSUUID) values (4,to_timestamp('29-Jun -18 12.50.00.737000000 PM','DD-MON-RR HH.MI.SS.FF AM'),to_timestamp('29-Jun -18 01.09.47.373000000 PM','DD-MON-RR HH.MI.SS.FF AM'),to_timestamp('29-Jun -18 01.18.01.529000000 PM','DD-MON-RR HH.MI.SS.FF AM'),'2',8,8,8,2,120.27,'2',null,null);
Insert into ERPUSER.RETURNORDERS (UUID,CREATETIME,CHECKTIME,ENDTIME,TYPE,CREATER,CHECKER,ENDER,SUPPLIERUUID,TOTALMONEY,STATE,WAYBILLSN,ORDERSUUID) values (21,to_timestamp('17-Aug -18 02.53.31.679000000 AM','DD-MON-RR HH.MI.SS.FF AM'),to_timestamp('17-Aug -18 03.48.17.965000000 AM','DD-MON-RR HH.MI.SS.FF AM'),null,'1',8,8,null,1,388000,'1',null,null);

---------------------------------------------------
--   END DATA FOR TABLE RETURNORDERS
---------------------------------------------------

---------------------------------------------------
--   DATA FOR TABLE GOODS
--   FILTER = none used
---------------------------------------------------
REM INSERTING into ERPUSER.GOODS
Insert into ERPUSER.GOODS (UUID,NAME,ORIGIN,PRODUCER,UNIT,INPRICE,OUTPRICE,GOODSTYPEUUID) values (5,'甜面酱','北京','七必居','袋',4.11,6.33,3);
Insert into ERPUSER.GOODS (UUID,NAME,ORIGIN,PRODUCER,UNIT,INPRICE,OUTPRICE,GOODSTYPEUUID) values (6,'可比克','北京','北京山寨食品有限公司','袋',3.88,6.33,4);
Insert into ERPUSER.GOODS (UUID,NAME,ORIGIN,PRODUCER,UNIT,INPRICE,OUTPRICE,GOODSTYPEUUID) values (7,'好吃点','河北','河北好吃点食品公司','袋',4.22,5.21,4);
Insert into ERPUSER.GOODS (UUID,NAME,ORIGIN,PRODUCER,UNIT,INPRICE,OUTPRICE,GOODSTYPEUUID) values (21,'香蕉','四川','水果','斤',1.2,2.2,2);
Insert into ERPUSER.GOODS (UUID,NAME,ORIGIN,PRODUCER,UNIT,INPRICE,OUTPRICE,GOODSTYPEUUID) values (41,'西瓜','四川','水果','斤',1,2.5,2);

---------------------------------------------------
--   END DATA FOR TABLE GOODS
---------------------------------------------------

---------------------------------------------------
--   DATA FOR TABLE RETURNORDERDETAIL
--   FILTER = none used
---------------------------------------------------
REM INSERTING into ERPUSER.RETURNORDERDETAIL
Insert into ERPUSER.RETURNORDERDETAIL (UUID,GOODSUUID,GOODSNAME,PRICE,NUM,MONEY,ENDTIME,ENDER,STOREUUID,STATE,ORDERSUUID) values (1,5,'甜面酱',4.11,100,411,to_timestamp('29-Jun -18 12.05.42.243000000 AM','DD-MON-RR HH.MI.SS.FF AM'),8,1,'1',1);
Insert into ERPUSER.RETURNORDERDETAIL (UUID,GOODSUUID,GOODSNAME,PRICE,NUM,MONEY,ENDTIME,ENDER,STOREUUID,STATE,ORDERSUUID) values (2,6,'可比克',3.88,500,1940,to_timestamp('29-Jun -18 12.07.00.583000000 AM','DD-MON-RR HH.MI.SS.FF AM'),8,1,'1',1);
Insert into ERPUSER.RETURNORDERDETAIL (UUID,GOODSUUID,GOODSNAME,PRICE,NUM,MONEY,ENDTIME,ENDER,STOREUUID,STATE,ORDERSUUID) values (3,6,'可比克',3.88,200,776,to_timestamp('29-Jun -18 12.23.33.954000000 PM','DD-MON-RR HH.MI.SS.FF AM'),8,1,'1',2);
Insert into ERPUSER.RETURNORDERDETAIL (UUID,GOODSUUID,GOODSNAME,PRICE,NUM,MONEY,ENDTIME,ENDER,STOREUUID,STATE,ORDERSUUID) values (4,5,'甜面酱',4.11,1,4.11,to_timestamp('29-Jun -18 11.14.47.410000000 AM','DD-MON-RR HH.MI.SS.FF AM'),8,1,'1',3);
Insert into ERPUSER.RETURNORDERDETAIL (UUID,GOODSUUID,GOODSNAME,PRICE,NUM,MONEY,ENDTIME,ENDER,STOREUUID,STATE,ORDERSUUID) values (22,6,'可比克',6.33,2,12.66,null,null,null,'0',22);
Insert into ERPUSER.RETURNORDERDETAIL (UUID,GOODSUUID,GOODSNAME,PRICE,NUM,MONEY,ENDTIME,ENDER,STOREUUID,STATE,ORDERSUUID) values (5,6,'可比克',6.33,19,120.27,to_timestamp('29-Jun -18 01.18.01.529000000 PM','DD-MON-RR HH.MI.SS.FF AM'),8,1,'1',4);
Insert into ERPUSER.RETURNORDERDETAIL (UUID,GOODSUUID,GOODSNAME,PRICE,NUM,MONEY,ENDTIME,ENDER,STOREUUID,STATE,ORDERSUUID) values (21,6,'可比克',3.88,100000,388000,null,null,null,'0',21);

---------------------------------------------------
--   END DATA FOR TABLE RETURNORDERDETAIL
---------------------------------------------------
--------------------------------------------------------
--  Constraints for Table DEP
--------------------------------------------------------

  ALTER TABLE "ERPUSER"."DEP" ADD PRIMARY KEY ("UUID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "ERP_TS"  ENABLE;



--------------------------------------------------------
--  Constraints for Table GOODSTYPE
--------------------------------------------------------

  ALTER TABLE "ERPUSER"."GOODSTYPE" ADD PRIMARY KEY ("UUID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "ERP_TS"  ENABLE;

--------------------------------------------------------
--  Constraints for Table MENU
--------------------------------------------------------

  ALTER TABLE "ERPUSER"."MENU" ADD PRIMARY KEY ("MENUID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "ERP_TS"  ENABLE;










--------------------------------------------------------
--  DDL for Index SYS_C0011181
--------------------------------------------------------

  CREATE UNIQUE INDEX "ERPUSER"."SYS_C0011181" ON "ERPUSER"."DEP" ("UUID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "ERP_TS" ;
--------------------------------------------------------
--  DDL for Index SYS_C0011187
--------------------------------------------------------

  CREATE UNIQUE INDEX "ERPUSER"."SYS_C0011187" ON "ERPUSER"."GOODSTYPE" ("UUID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "ERP_TS" ;
--------------------------------------------------------
--  DDL for Index SYS_C0011191
--------------------------------------------------------

  CREATE UNIQUE INDEX "ERPUSER"."SYS_C0011191" ON "ERPUSER"."MENU" ("MENUID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "ERP_TS" ;

--------------------------------------------------------
--  Ref Constraints for Table EMP
--------------------------------------------------------

  ALTER TABLE "ERPUSER"."EMP" ADD CONSTRAINT "FK5W2BQ1T9MBVUC7XGYBBITYYM0" FOREIGN KEY ("DEPUUID")
    REFERENCES "ERPUSER"."DEP" ("UUID") ENABLE;

--------------------------------------------------------
--  Ref Constraints for Table GOODS
--------------------------------------------------------

  ALTER TABLE "ERPUSER"."GOODS" ADD CONSTRAINT "FKIRP2PCGAAIUXER5O7VGI10Y8S" FOREIGN KEY ("GOODSTYPEUUID")
    REFERENCES "ERPUSER"."GOODSTYPE" ("UUID") ENABLE;


--------------------------------------------------------
--  Ref Constraints for Table MENU
--------------------------------------------------------

  ALTER TABLE "ERPUSER"."MENU" ADD CONSTRAINT "FKQCF9GEM97GQA5QJM4D3ELCQT5" FOREIGN KEY ("PID")
    REFERENCES "ERPUSER"."MENU" ("MENUID") ENABLE;










--------------------------------------------------------
--  DDL for View VIEW_STOREALERT
--------------------------------------------------------

  CREATE OR REPLACE FORCE VIEW "ERPUSER"."VIEW_STOREALERT" ("UUID", "NAME", "STORENUM", "OUTNUM") AS 
  select a.uuid,a.name,a.storenum,b.outnum from (
  select g.uuid,g.name,sum(nvl(num,0)) storenum from goods g, storedetail s
  where g.uuid = s.goodsuuid(+)
  group by g.uuid,g.name
) a, (
  select ol.goodsuuid,sum(ol.num) as outnum from orderdetail ol, orders s
  where s.uuid=ol.ordersuuid
  and s.type='2' and ol.state='0'
  group by ol.goodsuuid
) b
where a.uuid =b.goodsuuid;
